### PR TITLE
default select option with empty string value

### PR DESCRIPTION
**Pull request by vladsavchuk**
For example, if I need to reset value to NULL in DB, instead of putting "0"

### CODE REVIEW

**Comment by osalabs** [comment]
then better name it `is_option_empty`

**Comment by vladsavchuk** [comment]
Probably  it'd be better to adopt these names:
`is_option0_zero`
`is_option0_empty`
`option0_caption`

the last one is to control the title of option 0. 

What do you think? Should I prepare a new pull-request?

**Comment by osalabs** [comment]
`is_option0` is already reading as "is option zero", so the reasonable name is `is_option_empty`.
Also NULL is not recommended default value for fields (best practice is to have default 0 value), so it's OK to have more lengthy name.

Why `option0_cation` if it's about title?  It could be `option0_title` then.

**Comment by vladsavchuk** [comment]
I'm reading `is_option0` as `<option>` child html element with 0-index.
I understand about NULL, the existed DB has NULL or INT fields. And also I have non-numeric select values to save into DB, so it'd be more appropriate to receive empty string rather that zero.

`title` is good. Does the "caption" != "title"? It's like a table caption. I've never heard: "Table title?" Select is the list, so probably the "caption" is better for it.

**Comment by osalabs** [comment]
if you will make `is_option_empty` and `option0_title`, `option_empty_title` - I would merge and close this.

**Comment by osalabs** [comment]
Updated main branch, so now:
`is_option0` - allows to have `<option value="0">`
`is_option_empty` - allows to have option `<option value="">`
`option0_title` - allows to override default "- select -" title for 0/empty option

**Pull request closed without merging**
